In [35]:
import pandas as pd

In [36]:
df = pd.read_csv(r"C:\Users\otabek.khamidov\Desktop\Data Analytics\Alex-Data_Analyst_Bootcamp\Pandas\Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [37]:
# group by orqali, Takrorlanmas data ni yig'ishimiz uchun filt vazifasini bajaradi
df.groupby("Base Flavor")

In [38]:
grouped = df.groupby("Base Flavor")
grouped

In [40]:
df.groupby("Base Flavor").count()
# Base Flavor ga tegishli ma'lumotlar sonini hisoblaydi

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [44]:
# Base Flavor ga tegishli ma'lumotlar minimumini hisoblaydi
df.groupby("Base Flavor").min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [43]:
# Base Flavor ga tegishli ma'lumotlar maximumini hisoblaydi
df.groupby("Base Flavor").max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [45]:
# Base Flavor ga tegishli ma'lumotlar yig'indisini hisoblaydi
df.groupby("Base Flavor").sum()

,Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Base Flavor,,,,,
Chocolate,ChocolateRocky RoadChocolte Fudge Brownie,YesYesYes,25.2,21.7,47.1
Vanilla,Mint Chocolate ChipVanillaCookie DoughPistachi...,YesNoYesNoYesNo,34.2,33.9,68.1

In [30]:
import pandas as pd

# Ma'lumotlar
data = {
    'yosh': [23, 45, 12, 36, 52],
    'daromad': [5000, 7000, 2000, 6500, 8000]
}
df = pd.DataFrame(data)

# Aggregation
natija = df.aggregate({
    'yosh': ['min', 'max', 'mean'],
    'daromad': ['min', 'max', 'mean']
})

print(natija)

      yosh  daromad
min   12.0   2000.0
max   52.0   8000.0
mean  33.6   5700.0

In [51]:
df.groupby("Base Flavor").agg({
    "Flavor Rating" : ["min", "max", "sum", "mean"]
})

            Flavor Rating
                      min   max   sum mean
Base Flavor
Chocolate             8.2   8.8  25.2  8.4
Vanilla               2.3  10.0  34.2  5.7

In [52]:
df.groupby("Base Flavor").agg({
    "Flavor Rating" : ["min", "max", "sum", "mean"],
    "Texture Rating" : ["min", "max", "sum", "mean"]
})

            Flavor Rating                  Texture Rating
                      min   max   sum mean            min  max   sum      mean
Base Flavor
Chocolate             8.2   8.8  25.2  8.4            7.0  7.6  21.7  7.233333
Vanilla               2.3  10.0  34.2  5.7            3.4  8.0  33.9  5.650000

In [54]:
df.groupby(["Base Flavor", "Liked"]).agg({
    "Flavor Rating" : ["min", "max", "sum", "mean"],
    "Texture Rating" : ["min", "max", "sum", "mean"]
})

                  Flavor Rating                  Texture Rating             \
                            min   max   sum mean            min  max   sum
Base Flavor Liked
Chocolate   Yes             8.2   8.8  25.2  8.4            7.0  7.6  21.7
Vanilla     No              2.3   4.7  10.8  3.6            3.4  5.0  13.4
            Yes             6.5  10.0  23.4  7.8            6.0  8.0  20.5


                       mean
Base Flavor Liked
Chocolate   Yes    7.233333
Vanilla     No     4.466667
            Yes    6.833333

In [55]:
df.groupby("Base Flavor").describe()

            Flavor Rating                                             \
                    count mean       std  min    25%  50%  75%   max
Base Flavor
Chocolate             3.0  8.4  0.346410  8.2  8.200  8.2  8.5   8.8
Vanilla               6.0  5.7  2.710719  2.3  4.025  5.6  6.8  10.0

            Texture Rating            ...             Total Rating         \
                     count      mean  ...    75%  max        count   mean
Base Flavor                           ...
Chocolate              3.0  7.233333  ...  7.350  7.6          3.0  15.70
Vanilla                6.0  5.650000  ...  6.375  8.0          6.0  11.35


                  std   min     25%   50%     75%   max
Base Flavor
Chocolate    0.781025  15.2  15.250  15.3  15.950  16.6
Vanilla      4.263684   5.7   9.025  11.1  13.175  18.0

[2 rows x 24 columns]

In [56]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

In [57]:
df.groupby("Liked")

In [61]:
df.groupby("Liked").sum()

,Flavor,Base Flavor,Flavor Rating,Texture Rating,Total Rating
Liked,,,,,
No,VanillaPistachioNeapolitan,VanillaVanillaVanilla,10.8,13.4,24.2
Yes,Mint Chocolate ChipChocolateCookie DoughRocky ...,VanillaChocolateVanillaChocolateVanillaChocolate,48.6,42.2,91.0

In [62]:
df.groupby("Liked").agg({
    "Total Rating" : ["max", "min"]
})

      Base Flavor
              max        min
Liked
No        Vanilla    Vanilla
Yes       Vanilla  Chocolate