In [1]:
import pandas as pd

In [4]:
df = pd.read_csv (r"C:\Users\otabek.khamidov\Desktop\Data Analytics\Alex-Data_Analyst_Bootcamp\Pandas\world_population.csv")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [6]:
# index_col = "" -> bu orqali birinchi index Country dan boshlanadigan qildik.
df = pd.read_csv (r"C:\Users\otabek.khamidov\Desktop\Data Analytics\Alex-Data_Analyst_Bootcamp\Pandas\world_population.csv", index_col = "Country")
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
# bizga hozir Country index bop' qoldi. Lekin bizga boshida kiritgan df kerak.
df.reset_index(inplace = True)
df

,index,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [18]:
# index nomini o'zgartirishning ikkinchi usuli
df.set_index("Country", inplace = True)
df

,index,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,0,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,1,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,2,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,3,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,4,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,229,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,230,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,231,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,232,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,233,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [19]:
# Yemen indexiga tegishli barcha elementlar chiqadi.
df.loc["Yemen"]

index                                 231
CCA3                                  YEM
Capital                             Sanaa
Continent                            Asia
2022 Population                33696614.0
2020 Population                32284046.0
2015 Population                28516545.0
2010 Population                24743946.0
2000 Population                18628700.0
1990 Population                13375121.0
1980 Population                 9204938.0
1970 Population                 6843607.0
Area (km²)                       527968.0
Density (per km²)                 63.8232
Growth Rate                        1.0217
World Population Percentage          0.42
Name: Yemen, dtype: object

In [12]:
# Yemen indexiga tegishli barcha elementlar chiqadi.
df.iloc[-3]

Rank                                   46
CCA3                                  YEM
Capital                             Sanaa
Continent                            Asia
2022 Population                33696614.0
2020 Population                32284046.0
2015 Population                28516545.0
2010 Population                24743946.0
2000 Population                18628700.0
1990 Population                13375121.0
1980 Population                 9204938.0
1970 Population                 6843607.0
Area (km²)                       527968.0
Density (per km²)                 63.8232
Growth Rate                        1.0217
World Population Percentage          0.42
Name: Yemen, dtype: object

In [21]:
# bizga hozir Country index bo'p qoldi. Lekin bizga boshida kiritgan df kerak.
df.reset_index(inplace = True)
df

,Country,index,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,0,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,1,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,2,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,3,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,4,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,229,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,230,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,231,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,232,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,233,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [37]:
df = pd.read_csv (r"C:\Users\otabek.khamidov\Desktop\Data Analytics\Alex-Data_Analyst_Bootcamp\Pandas\world_population.csv")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [38]:
df.set_index(["Country", "Capital"], inplace = True)
df

,,Rank,CCA3,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,Capital,,,,,,,,,,,,,,,
Afghanistan,Kabul,36,AFG,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,Tirana,138,ALB,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,Algiers,34,DZA,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,Pago Pago,213,ASM,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,Andorra la Vella,203,AND,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,Mata-Utu,226,WLF,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,El Aaiún,172,ESH,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,Sanaa,46,YEM,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,Lusaka,63,ZMB,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,Harare,74,ZWE,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [46]:
# sort indexing 
df.sort_index(ascending = True)

,,Rank,CCA3,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,Capital,,,,,,,,,,,,,,,
Afghanistan,Kabul,36,AFG,Asia,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,Tirana,138,ALB,Europe,2.842321e+06,2.866849e+06,2.882481e+06,2.913399e+06,3.182021e+06,3.295066e+06,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,Algiers,34,DZA,Africa,4.490322e+07,4.345167e+07,3.954315e+07,3.585634e+07,3.077462e+07,2.551807e+07,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,Pago Pago,213,ASM,Oceania,4.427300e+04,4.618900e+04,5.136800e+04,5.484900e+04,5.823000e+04,4.781800e+04,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,Andorra la Vella,203,AND,Europe,7.982400e+04,7.770000e+04,7.174600e+04,7.151900e+04,6.609700e+04,5.356900e+04,35611.0,19860.0,468.0,170.5641,1.0100,0.00
Angola,Luanda,42,AGO,Africa,3.558899e+07,3.342848e+07,2.812772e+07,2.336418e+07,1.639406e+07,1.182864e+07,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Anguilla,The Valley,224,AIA,North America,1.585700e+04,1.558500e+04,1.452500e+04,1.317200e+04,1.104700e+04,8.316000e+03,6560.0,6283.0,91.0,174.2527,1.0066,0.00
Antigua and Barbuda,Saint John’s,201,ATG,North America,9.376300e+04,9.266400e+04,8.994100e+04,8.569500e+04,7.505500e+04,6.332800e+04,64888.0,64516.0,442.0,212.1335,1.0058,0.00
Argentina,Buenos Aires,33,ARG,South America,4.551032e+07,4.503603e+07,4.325706e+07,4.110012e+07,3.707077e+07,3.263766e+07,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
Armenia,Yerevan,140,ARM,Asia,2.780469e+06,2.805608e+06,2.878595e+06,2.946293e+06,3.168523e+06,3.556539e+06,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
Aruba,Oranjestad,198,ABW,North America,1.064450e+05,1.065850e+05,1.042570e+05,1.003410e+05,8.910100e+04,6.571200e+04,62267.0,59106.0,180.0,591.3611,0.9991,0.00
Australia,Canberra,55,AUS,Oceania,2.617741e+07,2.567005e+07,2.382024e+07,2.201917e+07,1.901796e+07,1.704800e+07,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33
Austria,Vienna,99,AUT,Europe,8.939617e+06,8.907777e+06,8.642421e+06,8.362829e+06,8.010428e+06,7.678729e+06,7547561.0,7465301.0,83871.0,106.5877,1.0020,0.11
Azerbaijan,Baku,91,AZE,Asia,1.035807e+07,NaN,9.863480e+06,9.237202e+06,8.190337e+06,7.427836e+06,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
Bahamas,Nassau,176,BHS,North America,4.099840e+05,4.064710e+05,3.926970e+05,3.732720e+05,3.250140e+05,2.706790e+05,223752.0,179129.0,13943.0,29.4043,1.0051,0.01
Bahrain,Manama,154,BHR,Asia,1.472233e+06,1.477469e+06,1.362142e+06,1.213645e+06,7.114420e+05,5.174180e+05,362595.0,222555.0,765.0,1924.4876,1.0061,0.02
Bangladesh,Dhaka,8,BGD,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
Barbados,Bridgetown,186,BRB,North America,2.816350e+05,2.806930e+05,2.780830e+05,2.747110e+05,2.646570e+05,2.588680e+05,253575.0,241397.0,430.0,654.9651,1.0015,0.00
Belarus,Minsk,96,BLR,Europe,9.534954e+06,9.633740e+06,9.700609e+06,9.731427e+06,1.025648e+07,1.042852e+07,9817257.0,9170786.0,207600.0,45.9295,0.9955,0.12
Belgium,Brussels,81,BEL,Europe,1.165593e+07,1.156172e+07,1.124830e+07,1.087795e+07,1.026434e+07,9.959560e+06,9828986.0,9629376.0,30528.0,381.8111,1.0038,0.15
Belize,Belmopan,177,BLZ,North America,4.052720e+05,3.949210e+05,3.598710e+05,3.221060e+05,2.404060e+05,1.825890e+05,145133.0,120905.0,22966.0,17.6466,1.0131,0.01
Benin,Porto-Novo,77,BEN,Africa,1.335286e+07,1.264312e+07,1.093278e+07,9.445710e+06,6.998023e+06,5.133419e+06,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
Bermuda,Hamilton,206,BMU,North America,6.418400e+04,6.403100e+04,6.314400e+04,6.344700e+04,6.137100e+04,5.747000e+04,53565.0,52019.0,54.0,1188.5926,1.0000,0.00
Bhutan,Thimphu,165,BTN,Asia,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
Bolivia,Sucre,80,BOL,South America,1.222411e+07,1.193616e+07,1.109008e+07,1.022327e+07,8.592656e+06,7.096194e+06,5736088.0,4585693.0,1098581.0,11.1272,1.0120,0.15
Bosnia and Herzegovina,Sarajevo,137,BIH,Europe,3.233526e+06,3.318407e+06,3.524324e+06,3.811088e+06,4.179350e+06,4.494310e+06,4199820.0,3815561.0,51209.0,63.1437,0.9886,0.04
Botswana,Gaborone,144,BWA,Africa,2.630296e+06,2.546402e+06,2.305171e+06,2.091664e+06,1.726985e+06,1.341474e+06,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
Brazil,Brasilia,7,BRA,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
British Virgin Islands,Road Town,221,VGB,North America,3.130500e+04,3.091000e+04,2.936600e+04,2.755600e+04,2.010400e+04,1.561700e+04,11109.0,9581.0,151.0,207.3179,1.0059,0.00
Brunei,Bandar Seri Begawan,175,BRN,Asia,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
Bulgaria,Sofia,108,BGR,Europe,6.781953e+06,6.979175e+06,7.309253e+06,7.592273e+06,8.097691e+06,8.767778e+06,8980606.0,8582950.0,110879.0,61.1654,0.9849,0.09
Burkina Faso,Ouagadougou,58,BFA,Africa,2.267376e+07,2.152263e+07,1.871802e+07,1.611684e+07,1.188289e+07,9.131361e+06,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
Burundi,Bujumbura,78,BDI,Africa,1.288958e+07,1.222023e+07,1.072715e+07,9.126605e+06,6.307659e+06,5.483793e+06,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
Cambodia,Phnom Penh,73,KHM,Asia,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
Cameroon,Yaounde,53,CMR,Africa,2.791454e+07,2.649109e+07,2.301265e+07,1.987804e+07,1.509159e+07,1.143052e+07,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
Canada,Ottawa,39,CAN,North America,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
Cape Verde,Praia,171,CPV,Africa,5.931490e+05,5.826400e+05,5.521660e+05,5.212120e+05,4.582510e+05,3.645630e+05,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
Cayman Islands,George Town,205,CYM,North America,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00
Central African Republic,Bangui,117,CAF,Africa,5.579144e+06,5.343020e+06,4.819333e+06,4.660067e+06,3.759170e+06,2.809221e+06,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
Chad,N'Djamena,69,TCD,Africa,1.772332e+07,1.664470e+07,1.414027e+07,1.189473e+07,8.259137e+06,5.827069e+06,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
Chile,Santiago,65,CHL,South America,1.960373e+07,1.930032e+07,1.787012e+07,1.700416e+07,1.535180e+07,1.334287e+07,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
China,Beijing,1,CHN,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
Colombia,Bogota,28,COL,South America,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
Comoros,Moroni,163,COM,Africa,8.367740e+05,8.061660e+05,7.302160e+05,6.560240e+05,5.367580e+05,4.311190e+05,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
Cook Islands,Avarua,223,COK,Oceania,1.701100e+04,1.702900e+04,1.769500e+04,1.721200e+04,1.589700e+04,1.712300e+04,17651.0,20470.0,236.0,72.0805,1.0005,0.00
Costa Rica,San José,124,CRI,North America,5.180829e+06,5.123105e+06,4.895242e+06,4.622252e+06,3.979193e+06,3.158253e+06,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06
Croatia,Zagreb,130,HRV,Europe,4.030358e+06,4.096868e+06,4.254815e+06,4.368682e+06,4.548434e+06,4.873707e+06,4680144.0,4492638.0,56594.0,71.2153,0.9927,0.05
Cuba,Havana,85,CUB,North America,1.121219e+07,1.130070e+07,1.133989e+07,1.129042e+07,1.110579e+07,1.062668e+07,9809107.0,8869636.0,109884.0,102.0366,0.9961,0.14
Curacao,Willemstad,189,CUW,North America,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00
Cyprus,Nicosia,158,CYP,Europe,1.251488e+06,1.237537e+06,1.187280e+06,1.129686e+06,9.482370e+05,7.885000e+05,679327.0,640804.0,9251.0,135.2814,1.0059,0.02
Czech Republic,Prague,88,CZE,Europe,1.049399e+07,1.053095e+07,1.052380e+07,1.046475e+07,1.023471e+07,1.030119e+07,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13
DR Congo,Kinshasa,15,COD,Africa,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,4.861632e+07,3.598754e+07,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
Denmark,Copenhagen,115,DNK,Europe,5.882261e+06,5.825641e+06,5.677796e+06,5.550849e+06,5.340655e+06,5.144623e+06,5125392.0,4922963.0,43094.0,136.4984,1.0048,0.07
Djibouti,Djibouti,160,DJI,Africa,1.120849e+06,1.090156e+06,1.006259e+06,9.191990e+05,7.420330e+05,5.771730e+05,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
Dominica,Roseau,204,DMA,North America,7.273700e+04,7.199500e+04,7.000700e+04,6.875500e+04,6.834600e+04,6.948100e+04,72978.0,68895.0,751.0,96.8535,1.0045,0.00
Dominican Republic,Santo Domingo,84,DOM,North America,1.122882e+07,1.099966e+07,1.040583e+07,9.775755e+06,8.540791e+06,7.129004e+06,5755800.0,4475871.0,48671.0,230.7087,1.0100,0.14
Ecuador,Quito,67,ECU,South America,1.800100e+07,1.758860e+07,1.619590e+07,1.498958e+07,1.262651e+07,1.044984e+07,8135845.0,6172215.0,276841.0,65.0229,1.0114,0.23
Egypt,Cairo,14,EGY,Africa,1.109901e+08,1.074651e+08,9.772380e+07,8.725241e+07,7.137137e+07,5.721463e+07,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
El Salvador,San Salvador,112,SLV,North America,6.336392e+06,6.292731e+06,6.231066e+06,6.114034e+06,5.958482e+06,5.367179e+06,4508992.0,3619090.0,21041.0,301.1450,1.0035,0.08
Equatorial Guinea,Malabo,152,GNQ,Africa,1.674908e+06,1.596049e+06,NaN,1.094524e+06,6.849770e+05,4.655490e+05,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
Eritrea,Asmara,132,ERI,Africa,3.684032e+06,3.555868e+06,3.340006e+06,3.147727e+06,2.392880e+06,2.149960e+06,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
Estonia,Tallinn,156,EST,Europe,1.326062e+06,1.329444e+06,1.314657e+06,1.331535e+06,1.396877e+06,1.570674e+06,1476983.0,1361999.0,45227.0,29.3201,0.9980,0.02
Eswatini,Mbabane,159,SWZ,Africa,NaN,1.180655e+06,1.133936e+06,1.099920e+06,1.030496e+06,8.540110e+05,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
Ethiopia,Addis Ababa,12,ETH,Africa,1.233799e+08,1.171909e+08,1.024719e+08,8.923779e+07,6.703187e+07,4.787807e+07,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Falkland Islands,Stanley,231,FLK,South America,3.780000e+03,3.747000e+03,3.408000e+03,3.187000e+03,3.080000e+03,2.332000e+03,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
Faroe Islands,Tórshavn,209,FRO,Europe,5.309000e+04,5.241500e+04,4.881600e+04,4.841000e+04,4.566000e+04,4.747900e+04,43054.0,38416.0,1393.0,38.1120,1.0038,0.00
Fiji,Suva,162,FJI,Oceania,9.297660e+05,9.204220e+05,9.172000e+05,9.051690e+05,8.325090e+05,7.804300e+05,644582.0,527634.0,18272.0,50.8847,1.0056,0.01
Finland,Helsinki,118,FIN,Europe,5.540745e+06,5.529468e+06,5.479461e+06,5.363271e+06,5.176209e+06,4.986545e+06,4779418.0,4606621.0,338424.0,16.3722,1.0009,0.07
France,Paris,23,FRA,Europe,6.462663e+07,6.448005e+07,6.380977e+07,6.244457e+07,5.866545e+07,5.641290e+07,53713830.0,50523586.0,551695.0,117.1419,1.0015,0.81
French Guiana,Cayenne,184,GUF,South America,3.045570e+05,2.909690e+05,2.570260e+05,2.284530e+05,1.643510e+05,1.139310e+05,66825.0,46484.0,83534.0,3.6459,1.0239,0.00
French Polynesia,Papeete,183,PYF,Oceania,3.062790e+05,3.019200e+05,2.917870e+05,2.837880e+05,2.509270e+05,2.110890e+05,163591.0,117891.0,4167.0,73.5011,1.0074,0.00
Gabon,Libreville,146,GAB,Africa,2.388992e+06,2.292573e+06,2.028517e+06,1.711105e+06,1.272935e+06,9.830280e+05,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
Gambia,Banjul,142,GMB,Africa,2.705992e+06,2.573995e+06,2.253133e+06,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
Georgia,Tbilisi,131,GEO,Asia,3.744385e+06,3.765912e+06,3.771132e+06,NaN,NaN,NaN,NaN,NaN,69700.0,53.7214,0.9964,0.05
Germany,Berlin,19,DEU,Europe,8.336984e+07,8.332899e+07,8.207323e+07,8.132509e+07,8.155168e+07,7.937020e+07,77786703.0,78294583.0,357114.0,233.4544,0.9995,1.05
Ghana,Accra,47,GHA,Africa,3.347587e+07,3.218040e+07,2.887094e+07,2.557472e+07,1.966550e+07,1.544698e+07,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Gibraltar,Gibraltar,219,GIB,Europe,3.264900e+04,3.270900e+04,3.252000e+04,3.126200e+04,2.774100e+04,2.731700e+04,28734.0,26685.0,6.0,5441.5000,0.9994,0.00
Greece,Athens,90,GRC,Europe,1.038497e+07,1.051223e+07,1.080664e+07,1.103378e+07,1.103811e+07,1.030226e+07,9307148.0,8544873.0,131990.0,78.6800,0.9942,0.13
Greenland,Nuuk,208,GRL,North America,5.646600e+04,5.602600e+04,5.589500e+04,5.635100e+04,5.618400e+04,5.559900e+04,50106.0,45434.0,2166086.0,0.0261,1.0040,0.00
Grenada,Saint George's,193,GRD,North America,1.254380e+05,1.236630e+05,1.189800e+05,1.140390e+05,1.074320e+05,9.904700e+04,94838.0,98794.0,344.0,364.6453,1.0066,0.00
Guadeloupe,Basse-Terre,178,GLP,North America,3.957520e+05,3.956420e+05,3.990890e+05,4.030720e+05,4.240670e+05,3.919510e+05,334234.0,318310.0,1628.0,243.0909,0.9992,0.00
Guam,Hagåtña,191,GUM,Oceania,1.717740e+05,1.692310e+05,1.679780e+05,1.649050e+05,1.601880e+05,1.382630e+05,110286.0,88300.0,549.0,312.8852,1.0073,0.00
Guatemala,Guatemala City,68,GTM,North America,1.784391e+07,1.736272e+07,1.600111e+07,1.454312e+07,1.173589e+07,9.084780e+06,6987767.0,5453208.0,108889.0,163.8725,1.0134,0.22
Guernsey,Saint Peter Port,207,GGY,Europe,6.330100e+04,6.279400e+04,6.162900e+04,6.078200e+04,5.911400e+04,5.772700e+04,52860.0,52656.0,78.0,811.5513,1.0037,0.00
Guinea,Conakry,75,GIN,Africa,1.385934e+07,1.320515e+07,1.162600e+07,1.027073e+07,8.336967e+06,6.354145e+06,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
Guinea-Bissau,Bissau,149,GNB,Africa,2.105566e+06,2.015828e+06,1.788919e+06,1.567220e+06,1.230849e+06,9.735510e+05,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
Guyana,Georgetown,164,GUY,South America,8.087260e+05,7.972020e+05,7.550310e+05,7.479320e+05,7.590510e+05,7.471160e+05,778176.0,705261.0,214969.0,3.7621,1.0052,0.01
Haiti,Port-au-Prince,82,HTI,North America,1.158500e+07,1.130680e+07,1.056376e+07,9.842880e+06,8.360225e+06,6.925331e+06,5646676.0,4680812.0,27750.0,417.4773,1.0120,0.15
Honduras,Tegucigalpa,89,HND,North America,1.043286e+07,1.012176e+07,9.294505e+06,8.450933e+06,6.656725e+06,5.053234e+06,3777990.0,2782753.0,112492.0,92.7431,1.0150,0.13
Hong Kong,Hong Kong,104,HKG,Asia,7.488865e+06,7.500958e+06,7.399838e+06,7.132438e+06,6.731195e+06,5.838574e+06,4978544.0,3955072.0,1104.0,6783.3922,0.9992,0.09
Hungary,Budapest,94,HUN,Europe,9.967308e+06,9.750573e+06,9.844246e+06,9.986825e+06,1.020206e+07,NaN,NaN,10315366.0,93028.0,107.1431,1.0265,0.12
Iceland,Reykjavík,179,ISL,Europe,3.728990e+05,3.666690e+05,3.310600e+05,3.183330e+05,2.814620e+05,NaN,NaN,204468.0,103000.0,3.6204,1.0069,0.00
India,New Delhi,2,IND,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
Indonesia,Jakarta,4,IDN,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
Iran,Tehran,17,IRN,Asia,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
Iraq,Baghdad,35,IRQ,Asia,4.449612e+07,4.255698e+07,3.775781e+07,3.126488e+07,2.462886e+07,1.765838e+07,13653369.0,9811347.0,438317.0,101.5158,1.0221,0.56
Ireland,Dublin,125,IRL,Europe,5.023109e+06,4.946119e+06,4.665760e+06,4.524585e+06,3.768950e+06,3.485374e+06,3391387.0,2937637.0,70273.0,71.4799,1.0073,0.06
Isle of Man,Douglas,202,IMN,Europe,8.451900e+04,8.404600e+04,8.359300e+04,8.382800e+04,7.556200e+04,6.886500e+04,64022.0,55298.0,572.0,147.7605,1.0030,0.00
Israel,Jerusalem,98,ISR,Asia,9.038309e+06,8.757489e+06,8.007778e+06,7.328445e+06,6.116958e+06,4.803254e+06,3744608.0,2907307.0,20770.0,435.1617,1.0155,0.11
Italy,Rome,25,ITA,Europe,5.903747e+07,5.950058e+07,6.023291e+07,5.982245e+07,5.696640e+07,5.675656e+07,56329482.0,53324036.0,301336.0,195.9191,0.9966,0.74
Ivory Coast,Yamoussoukro,52,CIV,Africa,2.816054e+07,2.681179e+07,2.359674e+07,2.112004e+07,1.679967e+07,1.191054e+07,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
Jamaica,Kingston,139,JAM,North America,2.827377e+06,2.820436e+06,2.794445e+06,2.733896e+06,2.612205e+06,2.392030e+06,2135546.0,1859091.0,10991.0,NaN,NaN,0.04
Japan,Tokyo,11,JPN,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
Jersey,Saint Helier,195,JEY,Europe,1.107780e+05,1.083190e+05,1.005610e+05,9.615100e+04,8.619200e+04,8.287400e+04,75124.0,68347.0,116.0,954.9828,1.0106,0.00
Jordan,Amman,83,JOR,Asia,1.128587e+07,1.092872e+07,9.494246e+06,6.931258e+06,5.056174e+06,3.480587e+06,2216903.0,1557374.0,89342.0,126.3221,1.0123,0.14
Kazakhstan,Nursultan,66,KAZ,Asia,1.939800e+07,1.897924e+07,1.783591e+07,1.662784e+07,1.523625e+07,1.686656e+07,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
Kenya,Nairobi,27,KEN,Africa,5.402749e+07,5.198578e+07,4.685149e+07,4.151790e+07,3.085161e+07,2.316227e+07,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
Kiribati,Tarawa,192,KIR,Oceania,1.312320e+05,1.264630e+05,1.167070e+05,1.079950e+05,8.882600e+04,7.512400e+04,60813.0,57437.0,811.0,161.8150,1.0183,0.00
Kuwait,Kuwait City,129,KWT,Asia,4.268873e+06,4.360444e+06,3.908743e+06,2.943356e+06,1.934901e+06,1.674938e+06,1493870.0,802786.0,17818.0,239.5821,1.0044,0.05
Kyrgyzstan,Bishkek,110,KGZ,Asia,6.630623e+06,6.424874e+06,5.914980e+06,5.483774e+06,4.935182e+06,4.394734e+06,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
Laos,Vientiane,103,LAO,Asia,7.529475e+06,7.319399e+06,6.787419e+06,6.323418e+06,5.430853e+06,4.314443e+06,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09
Latvia,Riga,151,LVA,Europe,1.850651e+06,1.897052e+06,1.991955e+06,2.101530e+06,2.392530e+06,2.689391e+06,2572037.0,2397414.0,64559.0,28.6660,0.9876,0.02
Lebanon,Beirut,119,LBN,Asia,5.489739e+06,5.662923e+06,6.398940e+06,4.995800e+06,4.320642e+06,3.593700e+06,2963702.0,2381791.0,10452.0,525.2334,0.9816,0.07
Lesotho,Maseru,147,LSO,Africa,2.305825e+06,2.254100e+06,2.118521e+06,2.022747e+06,1.998630e+06,1.798997e+06,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Liberia,Monrovia,121,LBR,Africa,5.302681e+06,5.087584e+06,4.612329e+06,4.019956e+06,2.895224e+06,2.209731e+06,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Libya,Tripoli,107,LBY,Africa,6.812341e+06,6.653942e+06,6.192235e+06,6.491988e+06,5.154790e+06,4.236983e+06,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Liechtenstein,Vaduz,216,LIE,Europe,3.932700e+04,3.875600e+04,3.735500e+04,3.592600e+04,3.302600e+04,2.876500e+04,25003.0,21089.0,160.0,245.7937,1.0074,0.00
Lithuania,Vilnius,141,LTU,Europe,2.750055e+06,2.820267e+06,2.963765e+06,3.139019e+06,3.599637e+06,3.785847e+06,3521206.0,3210147.0,65300.0,42.1142,0.9869,0.03
Luxembourg,Luxembourg,168,LUX,Europe,6.475990e+05,6.303990e+05,5.694080e+05,5.070700e+05,4.356280e+05,3.812670e+05,363741.0,339342.0,2586.0,250.4250,1.0129,0.01
Macau,Concelho de Macau,167,MAC,Asia,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
Madagascar,Antananarivo,50,MDG,Africa,2.961171e+07,2.822518e+07,2.485091e+07,2.173105e+07,1.621643e+07,1.188276e+07,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
Malawi,Lilongwe,62,MWI,Africa,2.040532e+07,1.937706e+07,1.693894e+07,1.471842e+07,1.122939e+07,9.539665e+06,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
Malaysia,Kuala Lumpur,45,MYS,Asia,3.393822e+07,3.319999e+07,3.106883e+07,NaN,NaN,1.751705e+07,13215707.0,10306508.0,330803.0,102.5934,1.0109,0.43
Maldives,Malé,174,MDV,Asia,5.237870e+05,5.144380e+05,4.355820e+05,NaN,NaN,2.249570e+05,164887.0,123243.0,300.0,1745.9567,1.0045,0.01

In [44]:
pd.set_option("display.max.rows", 235)

In [48]:
# sort indexing 
df.sort_index(ascending = False)

,,Rank,CCA3,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,Capital,,,,,,,,,,,,,,,
Zimbabwe,Harare,74,ZWE,Africa,1.632054e+07,1.566967e+07,1.415494e+07,1.283977e+07,1.183468e+07,1.011389e+07,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20
Zambia,Lusaka,63,ZMB,Africa,2.001768e+07,1.892772e+07,NaN,1.379209e+07,9.891136e+06,7.686401e+06,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Yemen,Sanaa,46,YEM,Asia,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Western Sahara,El Aaiún,172,ESH,Africa,5.759860e+05,5.560480e+05,4.918240e+05,4.132960e+05,2.703750e+05,1.785290e+05,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Wallis and Futuna,Mata-Utu,226,WLF,Oceania,1.157200e+04,1.165500e+04,1.218200e+04,1.314200e+04,1.472300e+04,1.345400e+04,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Vietnam,Hanoi,16,VNM,Asia,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
Venezuela,Caracas,51,VEN,South America,2.830170e+07,2.849045e+07,3.052972e+07,2.871502e+07,NaN,1.975058e+07,15210443.0,11355475.0,NaN,30.8820,1.0036,0.35
Vatican City,Vatican City,234,VAT,Europe,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,733.0,752.0,1.0,510.0000,0.9980,0.00
Vanuatu,Port-Vila,181,VUT,Oceania,3.267400e+05,3.116850e+05,2.764380e+05,2.454530e+05,1.920740e+05,1.508820e+05,118156.0,87019.0,12189.0,26.8061,1.0238,0.00
Uzbekistan,Tashkent,43,UZB,Asia,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
Uruguay,Montevideo,133,URY,South America,3.422794e+06,3.429086e+06,3.402818e+06,3.352651e+06,3.292224e+06,3.117012e+06,2953750.0,2790265.0,181034.0,18.9069,0.9990,0.04
United States Virgin Islands,Charlotte Amalie,200,VIR,North America,9.946500e+04,1.004420e+05,1.028030e+05,1.061420e+05,1.081850e+05,1.006850e+05,96640.0,63446.0,347.0,286.6427,0.9937,0.00
United States,"Washington, D.C.",3,USA,North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
United Kingdom,London,21,GBR,Europe,6.750894e+07,6.705947e+07,6.522436e+07,6.276004e+07,5.885004e+07,5.721044e+07,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
United Arab Emirates,Abu Dhabi,97,ARE,Asia,9.441129e+06,9.287289e+06,8.916899e+06,8.481771e+06,3.275333e+06,1.900151e+06,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
Ukraine,Kiev,38,UKR,Europe,3.970174e+07,4.390967e+07,4.498256e+07,4.568302e+07,4.887976e+07,5.158982e+07,49973920.0,47279086.0,603500.0,65.7858,0.9120,0.50
Uganda,Kampala,31,UGA,Africa,4.724958e+07,4.440461e+07,3.747736e+07,3.234173e+07,2.402070e+07,1.758663e+07,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Tuvalu,Funafuti,227,TUV,Oceania,1.131200e+04,1.106900e+04,1.087700e+04,1.055000e+04,9.638000e+03,9.182000e+03,7731.0,5814.0,26.0,435.0769,1.0096,0.00
Turks and Caicos Islands,Cockburn Town,212,TCA,North America,4.570300e+04,4.427600e+04,3.653800e+04,2.972600e+04,1.874400e+04,1.170900e+04,7598.0,5665.0,948.0,48.2099,1.0131,0.00
Turkmenistan,Ashgabat,111,TKM,Asia,6.430770e+06,6.250438e+06,5.766431e+06,5.267970e+06,4.569132e+06,3.720278e+06,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
Turkey,Ankara,18,TUR,Asia,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
Tunisia,Tunis,79,TUN,Africa,1.235612e+07,1.216172e+07,1.155778e+07,1.089506e+07,9.893316e+06,8.440023e+06,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
Trinidad and Tobago,Port-of-Spain,153,TTO,North America,1.531044e+06,1.518147e+06,1.460177e+06,1.410296e+06,1.332203e+06,1.266518e+06,1127852.0,988890.0,5130.0,NaN,1.0035,0.02
Tonga,Nuku‘alofa,197,TON,Oceania,1.068580e+05,1.052540e+05,1.061220e+05,1.073830e+05,1.026030e+05,9.872700e+04,96708.0,86484.0,747.0,143.0495,1.0079,0.00
Tokelau,Nukunonu,233,TKL,Oceania,1.871000e+03,1.827000e+03,1.454000e+03,1.367000e+03,1.666000e+03,1.669000e+03,1647.0,1714.0,12.0,155.9167,1.0119,0.00
Togo,Lomé,100,TGO,Africa,8.848699e+06,8.442580e+06,7.473229e+06,6.571855e+06,5.008035e+06,3.875947e+06,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
Timor-Leste,Dili,155,TLS,Asia,NaN,1.299995e+06,1.205813e+06,1.088486e+06,NaN,7.581060e+05,642224.0,554021.0,14874.0,90.1772,1.0154,0.02
Thailand,Bangkok,20,THA,Asia,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
Tanzania,Dodoma,22,TZA,Africa,6.549775e+07,6.170452e+07,5.254282e+07,4.511053e+07,3.446370e+07,2.620601e+07,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
Tajikistan,Dushanbe,95,TJK,Asia,9.952787e+06,9.543207e+06,8.524063e+06,7.621779e+06,6.272998e+06,5.417860e+06,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
Taiwan,Taipei,57,TWN,Asia,2.389339e+07,2.382146e+07,2.351214e+07,2.308308e+07,2.219473e+07,2.058617e+07,18100281.0,14957870.0,36193.0,660.1662,1.0014,0.30
Syria,Damascus,60,SYR,Asia,2.212525e+07,2.077260e+07,1.920518e+07,2.233756e+07,1.630765e+07,1.240900e+07,8898954.0,6319199.0,185180.0,119.4797,1.0376,0.28
Switzerland,Bern,101,CHE,Europe,8.740472e+06,8.638613e+06,8.281732e+06,7.822435e+06,7.182059e+06,6.711693e+06,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11
Sweden,Stockholm,87,SWE,Europe,1.054935e+07,1.036897e+07,9.849349e+06,9.381729e+06,8.871043e+06,8.548406e+06,8311763.0,8027702.0,450295.0,23.4276,1.0079,0.13
Suriname,Paramaribo,170,SUR,South America,6.180400e+05,6.070650e+05,5.754750e+05,5.460800e+05,4.789980e+05,4.127560e+05,375112.0,379918.0,163820.0,3.7727,1.0082,0.01
Sudan,Khartoum,32,SDN,Africa,4.687420e+07,4.444049e+07,3.817118e+07,3.373993e+07,2.629877e+07,2.109089e+07,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
Sri Lanka,Colombo,61,LKA,Asia,2.183214e+07,2.171508e+07,2.133670e+07,2.066856e+07,1.877637e+07,1.720409e+07,14943645.0,12388769.0,65610.0,332.7563,1.0027,0.27
Spain,Madrid,30,ESP,Europe,4.755863e+07,4.736381e+07,4.643134e+07,4.657277e+07,4.074165e+07,3.888989e+07,37491666.0,33792617.0,505992.0,93.9909,1.0015,0.60
South Sudan,Juba,86,SSD,Africa,1.091316e+07,1.060623e+07,1.119430e+07,NaN,6.114440e+06,4.750817e+06,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
South Korea,Seoul,29,KOR,Asia,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
South Africa,Pretoria,24,ZAF,Africa,5.989388e+07,5.880193e+07,5.587650e+07,5.178492e+07,4.681327e+07,3.987757e+07,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
Somalia,Mogadishu,70,SOM,Africa,1.759751e+07,1.653702e+07,1.376391e+07,1.202665e+07,8.721465e+06,6.999096e+06,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
Solomon Islands,Honiara,166,SLB,Oceania,7.242730e+05,6.911910e+05,6.126600e+05,5.403940e+05,4.299780e+05,3.241710e+05,233668.0,172833.0,28896.0,25.0648,1.0232,0.01
Slovenia,Ljubljana,148,SVN,Europe,2.119844e+06,2.117641e+06,2.080862e+06,2.057286e+06,1.984339e+06,1.986024e+06,1901570.0,1741286.0,20273.0,104.5649,1.0002,0.03
Slovakia,Bratislava,116,SVK,Europe,5.643453e+06,5.456681e+06,5.424444e+06,5.396424e+06,5.376690e+06,5.261305e+06,4973883.0,4522867.0,49037.0,115.0856,1.0359,0.07
Sint Maarten,Philipsburg,214,SXM,North America,4.417500e+04,4.362100e+04,4.020500e+04,3.303400e+04,3.048900e+04,2.784500e+04,12243.0,6260.0,34.0,1299.2647,1.0030,0.00
Singapore,Singapore,113,SGP,Asia,5.975689e+06,5.909869e+06,5.650018e+06,5.163590e+06,4.053602e+06,3.022209e+06,2400729.0,2061831.0,710.0,8416.4634,1.0058,0.07
Sierra Leone,Freetown,102,SLE,Africa,8.605718e+06,8.233969e+06,7.314773e+06,6.436698e+06,4.584067e+06,4.325388e+06,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
Seychelles,Victoria,196,SYC,Africa,1.071180e+05,1.055300e+05,9.924000e+04,9.240900e+04,8.006000e+04,7.105700e+04,65290.0,54379.0,452.0,236.9867,1.0061,0.00
Serbia,Belgrade,105,SRB,Europe,7.221365e+06,7.358005e+06,7.519496e+06,7.653748e+06,7.935022e+06,7.987529e+06,7777010.0,7193533.0,88361.0,81.7257,0.9897,0.09
Senegal,Dakar,72,SEN,Africa,1.731645e+07,1.643612e+07,1.435618e+07,1.253012e+07,9.704287e+06,7.536001e+06,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
Saudi Arabia,Riyadh,41,SAU,Asia,3.640882e+07,3.599711e+07,3.274985e+07,2.941193e+07,2.154739e+07,1.600476e+07,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
Sao Tome and Principe,São Tomé,187,STP,Africa,2.273800e+05,2.186410e+05,2.011240e+05,1.821380e+05,1.437140e+05,1.203430e+05,97210.0,77583.0,964.0,235.8714,1.0192,0.00
San Marino,San Marino,218,SMR,Europe,3.366000e+04,3.400700e+04,3.357000e+04,3.160800e+04,NaN,2.313200e+04,21346.0,18169.0,61.0,551.8033,0.9975,0.00
Samoa,Apia,188,WSM,Oceania,2.223820e+05,2.149290e+05,2.035710e+05,1.946720e+05,1.840080e+05,1.681860e+05,164905.0,142771.0,2842.0,78.2484,1.0165,0.00
Saint Vincent and the Grenadines,Kingstown,199,VCT,North America,1.039480e+05,1.046320e+05,1.064820e+05,1.093080e+05,1.138130e+05,1.124870e+05,107480.0,98459.0,389.0,267.2185,0.9963,0.00
Saint Pierre and Miquelon,Saint-Pierre,229,SPM,North America,5.862000e+03,5.906000e+03,5.978000e+03,6.052000e+03,6.274000e+03,6.324000e+03,6106.0,5537.0,242.0,24.2231,0.9964,0.00
Saint Martin,Marigot,220,MAF,North America,3.179100e+04,3.255200e+04,3.502000e+04,3.645800e+04,2.961000e+04,2.812700e+04,7776.0,5802.0,53.0,599.8302,0.9951,0.00
Saint Lucia,Castries,190,LCA,North America,1.798570e+05,1.792370e+05,1.756230e+05,1.709350e+05,1.595000e+05,1.423010e+05,121633.0,103090.0,616.0,291.9756,1.0011,0.00
Saint Kitts and Nevis,Basseterre,211,KNA,North America,4.765700e+04,4.764200e+04,4.779000e+04,4.740300e+04,4.546100e+04,4.063600e+04,43097.0,44968.0,261.0,182.5939,1.0011,0.00
Saint Barthelemy,Gustavia,228,BLM,North America,1.096700e+04,1.068100e+04,9.643000e+03,8.988000e+03,7.082000e+03,5.168000e+03,2983.0,2417.0,21.0,522.2381,1.0098,0.00
Rwanda,Kigali,76,RWA,Africa,1.377670e+07,1.314636e+07,1.164296e+07,1.030903e+07,8.109989e+06,7.319962e+06,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
Russia,Moscow,9,RUS,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
Romania,Bucharest,64,ROU,Europe,1.965927e+07,1.944204e+07,1.990608e+07,2.033521e+07,2.191988e+07,2.283623e+07,22125224.0,19922618.0,238391.0,82.4665,1.0171,0.25
Reunion,Saint-Denis,161,REU,Africa,9.740520e+05,9.578220e+05,9.224950e+05,8.901300e+05,7.854240e+05,6.589920e+05,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
Republic of the Congo,Brazzaville,114,COG,Africa,5.970424e+06,5.702174e+06,5.064386e+06,4.437884e+06,3.134030e+06,2.385435e+06,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
Qatar,Doha,143,QAT,Asia,2.695122e+06,2.760385e+06,2.414573e+06,1.713504e+06,6.459370e+05,4.416750e+05,277450.0,118007.0,11586.0,232.6189,1.0026,0.03
Puerto Rico,San Juan,136,PRI,North America,3.252407e+06,3.271564e+06,3.497335e+06,3.717922e+06,3.827108e+06,3.543776e+06,3214568.0,2737619.0,8870.0,366.6750,0.9989,0.04
Portugal,Lisbon,92,PRT,Europe,1.027086e+07,1.029819e+07,1.036544e+07,1.058840e+07,1.030063e+07,1.000735e+07,9785252.0,8683631.0,92090.0,111.5307,0.9981,0.13
Poland,Warsaw,37,POL,Europe,3.985714e+07,3.842837e+07,3.855315e+07,3.859735e+07,3.850443e+07,3.806426e+07,35521429.0,32482943.0,312679.0,127.4698,1.0404,0.50
Philippines,Manila,13,PHL,Asia,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
Peru,Lima,44,PER,South America,3.404959e+07,3.330476e+07,3.071186e+07,2.922957e+07,2.665444e+07,2.210910e+07,17492406.0,13562371.0,1285216.0,26.4933,1.0099,0.43
Paraguay,Asunción,109,PRY,South America,6.780744e+06,6.618695e+06,6.177950e+06,5.768613e+06,5.123819e+06,4.059195e+06,3078912.0,2408787.0,406752.0,16.6705,1.0115,0.09
Papua New Guinea,Port Moresby,93,PNG,Oceania,1.014262e+07,9.749640e+06,8.682174e+06,7.583269e+06,5.508297e+06,3.864972e+06,3104788.0,2489059.0,462840.0,21.9139,1.0194,0.13
Panama,Panama City,128,PAN,North America,4.408581e+06,4.294396e+06,3.957099e+06,3.623617e+06,3.001731e+06,2.449968e+06,1956987.0,1516188.0,75417.0,58.4561,1.0132,0.06
Palestine,Ramallah,122,PSE,Asia,5.250072e+06,5.019401e+06,4.484614e+06,3.992278e+06,3.139954e+06,2.124609e+06,1453620.0,1118241.0,6220.0,844.0630,1.0227,0.07
Palau,Ngerulmud,222,PLW,Oceania,NaN,1.797200e+04,1.779400e+04,1.854000e+04,1.972600e+04,1.529300e+04,12252.0,11366.0,459.0,39.3355,1.0017,0.00
Pakistan,Islamabad,5,PAK,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
Oman,Muscat,127,OMN,Asia,4.576298e+06,4.543399e+06,4.191776e+06,2.881914e+06,2.344253e+06,1.804524e+06,1017462.0,670693.0,309500.0,14.7861,1.0123,0.06
Norway,Oslo,120,NOR,Europe,NaN,5.379839e+06,NaN,4.889741e+06,4.491202e+06,4.241636e+06,4085776.0,3875546.0,323802.0,16.7828,1.0058,0.07
Northern Mariana Islands,Saipan,210,NFK,Oceania,4.955100e+04,4.958700e+04,5.151400e+04,5.408700e+04,8.033800e+04,4.800200e+04,17613.0,10143.0,464.0,106.7909,1.0014,0.00
North Macedonia,Skopje,150,MKD,Europe,2.093599e+06,2.111072e+06,2.107962e+06,2.093828e+06,2.037936e+06,2.044174e+06,1907023.0,1656783.0,25713.0,81.4218,0.9954,0.03
North Korea,Pyongyang,56,PRK,Asia,2.606942e+07,2.586747e+07,2.525802e+07,2.468644e+07,2.336706e+07,2.079952e+07,17973650.0,14996879.0,120538.0,216.2755,1.0038,0.33
Niue,Alofi,232,NIU,Oceania,1.934000e+03,1.942000e+03,1.847000e+03,1.812000e+03,2.074000e+03,2.533000e+03,3637.0,5185.0,260.0,7.4385,0.9985,0.00
Nigeria,Abuja,6,NGA,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
Niger,Niamey,54,NER,Africa,2.620798e+07,2.433364e+07,2.012812e+07,1.664754e+07,1.162266e+07,8.370647e+06,6173177.0,4669708.0,1267000.0,20.6851,1.0378,0.33
Nicaragua,Managua,106,NIC,North America,6.948392e+06,6.755895e+06,6.298598e+06,5.855734e+06,5.123222e+06,4.227820e+06,3303309.0,2444767.0,130373.0,53.2962,1.0143,0.09
New Zealand,Wellington,123,NZL,Oceania,5.185288e+06,5.061133e+06,4.590590e+06,4.346338e+06,3.855266e+06,3.397389e+06,3147168.0,2824061.0,270467.0,19.1716,1.0108,0.07
New Caledonia,Nouméa,185,NCL,Oceania,2.899500e+05,2.864030e+05,2.830320e+05,2.614260e+05,2.215370e+05,1.772640e+05,148599.0,110982.0,18575.0,15.6097,1.0075,0.00
Netherlands,Amsterdam,71,NLD,Europe,1.756401e+07,1.743456e+07,1.704111e+07,1.661712e+07,1.589914e+07,1.494455e+07,14130387.0,13037686.0,41850.0,419.6897,1.0036,0.22
Nepal,Kathmandu,49,NPL,Asia,3.054758e+07,2.934863e+07,2.761032e+07,2.716157e+07,2.455950e+07,1.961653e+07,15600442.0,12501285.0,147181.0,207.5511,1.0171,0.38
Nauru,Yaren,225,NRU,Oceania,1.266800e+04,1.231500e+04,1.118500e+04,1.024100e+04,1.037700e+04,9.598000e+03,7635.0,6663.0,21.0,603.2381,1.0125,0.00
Namibia,Windhoek,145,NAM,Africa,2.567012e+06,2.489098e+06,2.282704e+06,2.099271e+06,1.819141e+06,1.369011e+06,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
Myanmar,Nay Pyi Taw,26,MMR,Asia,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,1.0071,0.68
Mozambique,Maputo,48,MOZ,Africa,3.296952e+07,3.117824e+07,NaN,NaN,1.776850e+07,1.330346e+07,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
Morocco,Rabat,40,MAR,Africa,3.745797e+07,3.668877e+07,3.468046e+07,3.246486e+07,2.855442e+07,2.457081e+07,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
Montserrat,Brades,230,MSR,North America,4.390000e+03,4.500000e+03,5.059000e+03,4.938000e+03,5.138000e+03,1.080500e+04,11452.0,11402.0,102.0,43.0392,0.9939,0.00
Montenegro,Podgorica,169,MNE,Europe,6.270820e+05,6.290480e+05,6.339660e+05,6.310440e+05,6.333240e+05,6.214420e+05,589324.0,530268.0,13812.0,45.4012,0.9988,0.01
Mongolia,Ulaanbaatar,134,MNG,Asia,3.398366e+06,3.294335e+06,2.964749e+06,2.702520e+06,2.450979e+06,2.161433e+06,1697780.0,1293880.0,1564110.0,2.1727,1.0151,0.04
Monaco,Monaco,217,MCO,Europe,3.646900e+04,3.692200e+04,3.676000e+04,3.317800e+04,3.246500e+04,3.032900e+04,27076.0,24270.0,2.0,18234.5000,0.9941,0.00
Moldova,Chisinau,135,MDA,Europe,3.272996e+06,3.084847e+06,3.277388e+06,3.678186e+06,4.251573e+06,4.480199e+06,4103240.0,3711140.0,33846.0,96.7026,1.0691,0.04
Micronesia,Palikir,194,FSM,Oceania,1.141640e+05,1.121060e+05,1.094620e+05,1.075880e+05,1.117090e+05,9.860300e+04,76299.0,58989.0,702.0,162.6268,1.0091,0.00
Mexico,Mexico City,10,MEX,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
Mayotte,Mamoudzou,182,MYT,Africa,3.261010e+05,3.055870e+05,2.495450e+05,2.117860e+05,1.592150e+05,9.265900e+04,52233.0,35383.0,374.0,871.9278,1.0319,0.00
Mauritius,Port Louis,157,MUS,Africa,1.299469e+06,1.297828e+06,1.293153e+06,1.283330e+06,1.215930e+06,1.090290e+06,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
Mauritania,Nouakchott,126,MRT,Africa,4.736139e+06,4.498604e+06,3.946220e+06,3.419461e+06,2.695003e+06,2.006027e+06,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
Martinique,Fort-de-France,180,MTQ,North America,3.675070e+05,3.703910e+05,3.835150e+05,3.921810e+05,4.325430e+05,3.742710e+05,333786.0,326428.0,1128.0,325.8041,0.9965,0.00
Marshall Islands,Majuro,215,MHL,Oceania,4.156900e+04,4.341300e+04,4.941000e+04,5.341600e+04,5.422400e+04,4.604700e+04,31988.0,23969.0,181.0,229.6630,0.9886,0.00
Malta,Valletta,173,MLT,Europe,5.332860e+05,5.153570e+05,4.565790e+05,4.187550e+05,3.992120e+05,3.653920e+05,333587.0,315414.0,316.0,1687.6139,1.0124,0.01
Mali,Bamako,59,MLI,Africa,2.259359e+07,2.122404e+07,1.811291e+07,1.552918e+07,1.123910e+07,8.945026e+06,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
Maldives,Malé,174,MDV,Asia,5.237870e+05,5.144380e+05,4.355820e+05,NaN,NaN,2.249570e+05,164887.0,123243.0,300.0,1745.9567,1.0045,0.01
Malaysia,Kuala Lumpur,45,MYS,Asia,3.393822e+07,3.319999e+07,3.106883e+07,NaN,NaN,1.751705e+07,13215707.0,10306508.0,330803.0,102.5934,1.0109,0.43
Malawi,Lilongwe,62,MWI,Africa,2.040532e+07,1.937706e+07,1.693894e+07,1.471842e+07,1.122939e+07,9.539665e+06,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
Madagascar,Antananarivo,50,MDG,Africa,2.961171e+07,2.822518e+07,2.485091e+07,2.173105e+07,1.621643e+07,1.188276e+07,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
Macau,Concelho de Macau,167,MAC,Asia,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
Luxembourg,Luxembourg,168,LUX,Europe,6.475990e+05,6.303990e+05,5.694080e+05,5.070700e+05,4.356280e+05,3.812670e+05,363741.0,339342.0,2586.0,250.4250,1.0129,0.01
Lithuania,Vilnius,141,LTU,Europe,2.750055e+06,2.820267e+06,2.963765e+06,3.139019e+06,3.599637e+06,3.785847e+06,3521206.0,3210147.0,65300.0,42.1142,0.9869,0.03
Liechtenstein,Vaduz,216,LIE,Europe,3.932700e+04,3.875600e+04,3.735500e+04,3.592600e+04,3.302600e+04,2.876500e+04,25003.0,21089.0,160.0,245.7937,1.0074,0.00
Libya,Tripoli,107,LBY,Africa,6.812341e+06,6.653942e+06,6.192235e+06,6.491988e+06,5.154790e+06,4.236983e+06,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Liberia,Monrovia,121,LBR,Africa,5.302681e+06,5.087584e+06,4.612329e+06,4.019956e+06,2.895224e+06,2.209731e+06,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Lesotho,Maseru,147,LSO,Africa,2.305825e+06,2.254100e+06,2.118521e+06,2.022747e+06,1.998630e+06,1.798997e+06,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Lebanon,Beirut,119,LBN,Asia,5.489739e+06,5.662923e+06,6.398940e+06,4.995800e+06,4.320642e+06,3.593700e+06,2963702.0,2381791.0,10452.0,525.2334,0.9816,0.07
Latvia,Riga,151,LVA,Europe,1.850651e+06,1.897052e+06,1.991955e+06,2.101530e+06,2.392530e+06,2.689391e+06,2572037.0,2397414.0,64559.0,28.6660,0.9876,0.02
Laos,Vientiane,103,LAO,Asia,7.529475e+06,7.319399e+06,6.787419e+06,6.323418e+06,5.430853e+06,4.314443e+06,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09