In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\Users\otabek.khamidov\Desktop\Desktop\Data Analytics\Alex-Data_Analyst_Bootcamp\Pandas\LOTR.csv")
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [3]:
df2 = pd.read_csv(r"C:\Users\otabek.khamidov\Desktop\Desktop\Data Analytics\Alex-Data_Analyst_Bootcamp\Pandas\LOTR 2.csv")
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [4]:
# ikki df.ning ikkovida mavjud qatorlaridagi qiymatlarini beradi
df1.merge(df2, how = "inner")

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [6]:
# ikki df.ning ikkovidaga barcha qatorlaridagi qiymatlarini beradi, element yo'qlariga NaN qiymat beradi
df1.merge(df2, how = "outer")

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [8]:
# ikkinchi usul:
pd.merge(df1, df2, how = "inner")

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

In [9]:
# ikkinchi usul:
pd.merge(df1, df2, how = "outer")

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

In [10]:
# ikki df.ning birinchi berilgan df.ning barcha qatorlaridagi qiymatlarini beradi, element yo'qlariga NaN qiymat beradi
df1.merge(df2, how = "left")

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

In [11]:
# ikkinchi usul:
pd.merge(df1, df2, how = "left")

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

In [12]:
# ikki df.ning ikkinchi berilgan df.ning barcha qatorlaridagi qiymatlarini beradi, element yo'qlariga NaN qiymat beradi
df1.merge(df2, how = "right")

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

In [13]:
# ikkinchi usul:
pd.merge(df1, df2, how = "right")

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

In [14]:
df1.merge(df2, how = "cross")

    FellowshipID_x FirstName_x     Skills  FellowshipID_y FirstName_y   Age
0             1001       Frodo     Hiding            1001       Frodo    50
1             1001       Frodo     Hiding            1002     Samwise    39
2             1001       Frodo     Hiding            1006     Legolas  2931
3             1001       Frodo     Hiding            1007      Elrond  6520
4             1001       Frodo     Hiding            1008    Barromir    51
5             1002     Samwise  Gardening            1001       Frodo    50
6             1002     Samwise  Gardening            1002     Samwise    39
7             1002     Samwise  Gardening            1006     Legolas  2931
8             1002     Samwise  Gardening            1007      Elrond  6520
9             1002     Samwise  Gardening            1008    Barromir    51
10            1003     Gandalf     Spells            1001       Frodo    50
11            1003     Gandalf     Spells            1002     Samwise    39
12            1003     Gandalf     Spells            1006     Legolas  2931
13            1003     Gandalf     Spells            1007      Elrond  6520
14            1003     Gandalf     Spells            1008    Barromir    51
15            1004      Pippin  Fireworks            1001       Frodo    50
16            1004      Pippin  Fireworks            1002     Samwise    39
17            1004      Pippin  Fireworks            1006     Legolas  2931
18            1004      Pippin  Fireworks            1007      Elrond  6520
19            1004      Pippin  Fireworks            1008    Barromir    51

In [15]:
pd.merge(df1, df2, how = "cross")

    FellowshipID_x FirstName_x     Skills  FellowshipID_y FirstName_y   Age
0             1001       Frodo     Hiding            1001       Frodo    50
1             1001       Frodo     Hiding            1002     Samwise    39
2             1001       Frodo     Hiding            1006     Legolas  2931
3             1001       Frodo     Hiding            1007      Elrond  6520
4             1001       Frodo     Hiding            1008    Barromir    51
5             1002     Samwise  Gardening            1001       Frodo    50
6             1002     Samwise  Gardening            1002     Samwise    39
7             1002     Samwise  Gardening            1006     Legolas  2931
8             1002     Samwise  Gardening            1007      Elrond  6520
9             1002     Samwise  Gardening            1008    Barromir    51
10            1003     Gandalf     Spells            1001       Frodo    50
11            1003     Gandalf     Spells            1002     Samwise    39
12            1003     Gandalf     Spells            1006     Legolas  2931
13            1003     Gandalf     Spells            1007      Elrond  6520
14            1003     Gandalf     Spells            1008    Barromir    51
15            1004      Pippin  Fireworks            1001       Frodo    50
16            1004      Pippin  Fireworks            1002     Samwise    39
17            1004      Pippin  Fireworks            1006     Legolas  2931
18            1004      Pippin  Fireworks            1007      Elrond  6520
19            1004      Pippin  Fireworks            1008    Barromir    51

In [16]:
# column.ga qarab join qilish uchun:
pd.concat([df1, df2], join = "inner")

   FellowshipID FirstName
0          1001     Frodo
1          1002   Samwise
2          1003   Gandalf
3          1004    Pippin
0          1001     Frodo
1          1002   Samwise
2          1006   Legolas
3          1007    Elrond
4          1008  Barromir

In [17]:
# column.ga qarab join qilish uchun:
pd.concat([df1, df2], join = "outer")

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding     NaN
1          1002   Samwise  Gardening     NaN
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
0          1001     Frodo        NaN    50.0
1          1002   Samwise        NaN    39.0
2          1006   Legolas        NaN  2931.0
3          1007    Elrond        NaN  6520.0
4          1008  Barromir        NaN    51.0

In [18]:
# .append() orqali ham .concat() amalini qilsak bo'ladi, lekin .append() pandas yangi versiya qilgan vaqtda delete bo'ladi
df1.append(df2)

AttributeError: 'DataFrame' object has no attribute 'append'